--- #YAML:1.0
name:               Geo-Parse-OSM
version:            0.40_1
abstract:           OpenStreetMap XML file regexp parser
author:
    - liosha <liosha@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Encode:               0
    HTML::Parser:         0
    IO::Uncompress::AnyUncompress:  0
    List::MoreUtils:      0
    List::Util:           0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
